version: '3'
services:
  redis:
    profiles: ['prod']
    image: redis:7.2.1-alpine
    container_name: apt-tracker-redis
    hostname: redis
    restart: unless-stopped
  redis-dev:
    profiles: ['dev']
    image: redis:7.2.1-alpine
    container_name: apt-tracker-redis-dev
    hostname: redis
    restart: unless-stopped
    ports:
      - 6379:6379
  tracker:
    profiles: ['prod']
    image: apt-tracker
    container_name: apt-tracker
    restart: unless-stopped
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
